include:
  - file: /common.yml
    project: QubesOS/qubes-continuous-integration

stages:
  - test

variables:
  DEBUG: "1"

lint:
  extends: .lint
  stage: test
  rules:
    - if: $CI_COMMIT_REF_NAME == "test"
      when: always
    - when: manual
  variables:
    DIR: $PWD
