include:
  - file: /common.yml
    project: QubesOS/qubes-continuous-integration

stages:
  - prepare
  - test

variables:
  DEBUG: "1"

lint:
  extends: .lint
  stage: test
  rules:
    - if: $CI_COMMIT_REF_NAME == "test"
      when: always
    - when: manual
  variables:
    DIR: $PWD

mypy:
  stage: test
  rules:
    - if: $CI_COMMIT_REF_NAME == "test"
      when: always
    - when: manual
  image: fedora:latest
  tags:
    - vm
  before_script:
    - sudo dnf install -y python3-mypy python3-pip python3-pathspec git
    - sudo python3 -m pip install types-PyYAML types-python-dateutil
    - echo "Qubes Builder v2 branch '${CI_QUBES_BUILDER_BRANCH:-main}'"
    - git clone -b "${CI_QUBES_BUILDER_BRANCH:-main}" https://gitlab.com/QubesOS/qubes-builderv2.git
  script:
    - PYTHONPATH="$PWD/qubes-builderv2" MYPYPATH="$PWD/qubes-builderv2" mypy --install-types --non-interactive --junit-xml mypy.xml
  artifacts:
    reports:
      junit: mypy.xml

.pytest:
  stage: test
  rules:
    - if: $CI_COMMIT_REF_NAME == "test"
      when: always
    - when: manual
  tags:
    - qubes
    - vm
  artifacts:
    when: always
    paths:
      - results
  before_script:
    - sudo dnf install -y python3-pathspec python3-pytest sequoia-sq sequoia-sqv sequoia-chameleon-gnupg python3-github python3-psutil
  after_script:
    - mkdir $CI_PROJECT_DIR/results
    - cp -r ~/pytest-of-$USER/pytest-current/github-current/*.log $CI_PROJECT_DIR/results || true
    - cp -r ~/pytest-of-$USER/pytest-current/github-current/builder-github-logs $CI_PROJECT_DIR/results/

test-common:
  extends: .pytest
  script:
    - TMPDIR=~ pytest-3 -vvv --showlocals --color=yes tests/test_common.py

test-action-component:
  extends: .pytest
  script:
    - TMPDIR=~ pytest-3 -vvv --showlocals --color=yes tests/test_action.py -k test_action_component

test-action-template:
  extends: .pytest
  script:
    - TMPDIR=~ pytest-3 -vvv --showlocals --color=yes tests/test_action.py -k test_action_template

test-action-iso:
  extends: .pytest
  script:
    - TMPDIR=~ pytest-3 -vvv --showlocals --color=yes tests/test_action.py -k test_action_iso

test-rpc-parse:
  extends: .pytest
  script:
    - TMPDIR=~ pytest-3 -vvv --showlocals --color=yes tests/test_rpc.py -k _parse_

test-rpc-component:
  extends: .pytest
  script:
    - TMPDIR=~ pytest-3 -vvv --showlocals --color=yes tests/test_rpc.py -k "test_rpc_04 or test_rpc_05"

test-rpc-template:
  extends: .pytest
  script:
    - TMPDIR=~ pytest-3 -vvv --showlocals --color=yes tests/test_rpc.py -k "test_rpc_06 or test_rpc_07"

test-rpc-iso:
  extends: .pytest
  script:
    - TMPDIR=~ pytest-3 -vvv --showlocals --color=yes tests/test_rpc.py -k test_rpc_08

test-command:
  extends: .pytest
  script:
    - TMPDIR=~ pytest-3 -vvv --showlocals --color=yes tests/test_command.py

test-notify:
  extends: .pytest
  script:
    - TMPDIR=~ pytest-3 -vvv --showlocals --color=yes tests/test_notify.py
